### ISSUE TITLE
A question about glitch WebSockets.

### ISSUE THREAD

**Issue by iMrDJAi** [jarvis394/glitch-api#9]
Generally I see these records on my network logs when I disconnect my device:

![image](https://user-images.githubusercontent.com/42304709/88318978-6de4b800-cd13-11ea-9f9c-0bc2e5ae8c2b.png)

I'm wondering about their purpose. are they used to tell if the user is connected with the editor? and to keep the project up while that? am I right?

Can you give me an example about how to generate them using your library?

And thx.

**Comment by jarvis394** [comment]
Can you please give more details about what are you trying to achieve?

On your screenshot I can only see bunch of reconnecting websockets 🙃 (probably it happens due to client offline). Websockets are a data tunnel for the editor, so without it editor cannot work, therefore it  tries to reconnect WS.

There is an [example](https://github.com/jarvis394/glitch-api/blob/master/docs/examples/websockets.js) that shows the basic connection through WS to `ot` client. This example will generate such websocket connection you are (maybe) trying to get.

I'm not sure if it is going to keep the project up, but certainly it would spend Glitch's **project hours** because, as they say, you will spend them if you edit the project. Editor and your project are not connected - while you edit without any problems, your app could be down and not running at all.

Thank you for questioning!

**Comment by iMrDJAi** [comment]
Oh I got it, so these WebSockets connect the client with the editor, and the editor itself is not connected to the project.
I just asked because I was wondering about an alternative way to prevent the project from sleeping since pinging is not a solution anymore.
and about Glitch's project hours, 1000h/mo is enough to keep one project running all time, so this wouldn't be a problem.
